### ISSUE TITLE
Issues with new lazy provider and renderers

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box-flow#140]
I'm testing the recently merged lazy data provider feature, which effectively works loading data lazily but I'm experiencing some filter/rendering issues.

1. When filtering and then clearing the filter, the filtered items disappear (see demo below).
2. The filter does not always respect the server defined filter (in the demo below the server side filter is set to filter by e-mail, but the client filters by any matching text it founds in the item).

![lazy-combo-box-small](https://user-images.githubusercontent.com/851745/46903143-4b343700-ced1-11e8-9966-690dd03d20a5.gif)

Ping @pekam

**Comment by pekam** [comment]
Hi @heruan and thanks for testing the lazy loading! It's really great to get feedback asap, before we even managed to make a pre-release out of it. :D

For your issues:
1. I actually discovered the same bug, but it's not caused by lazy loading. It happens also with the old `ComboBox` using `ComponentRenderer`. Here's the ticket for it: #136
If you can use `TemplateRenderer` instead of `ComponentRenderer`, you can avoid this problem until it gets fixed.
2. It should definitely use the server-side filter if one is provided. There's a test for this, but maybe some of the method overloads manages to avoid this. Can you show me how you provided the filter?

**Comment by heruan** [comment]
I missed the other ticket, sorry! About the filtering, I have this data provider:

```java
class UserDataProvider extends AbstractBackEndDataProvider<User, UserFilter> {
   // ...
}

class UserFilter implements Specification<User> {
    // fields
    @Override
    public Predicate toPredicate(...) {
       // create a predicate based on field values
    }
}
```

and this is how I apply it:

```java
reporterField.setDataProvider(userDataProvider.withConvertedFilter(input -> {
    var filter = new UserFilter();
    filter.setEmailAddress(input);
    return filter;
});
```

but when I type something in the field, I don't event see the queries so it's like the filtering doesn't happen when there are few items; it seeems to work when there are many items though.

**Comment by heruan** [comment]
Another small issue (tell me if I need to open a new one) is when a `ComboBox` has a data provider set, it has the `x` icon to clear its value even if there is no value; the icon then disappears when you focus it.

**Comment by pekam** [comment]
I see.

Some background info: We ended up deciding that ComboBox should provide smoother UX with client-side filtering when possible, so in practice when these two conditions are met:
- The size of the data set is less than the page size (client has all the data immediately)
- The user has not defined a server-side filter

My implementation decides based on the used overload of `setItems` or `setDataProvider` if the user provided a server-side filter. You are using an overload of `setDataProvider` which doesn't take a filter as a parameter, so the ComboBox thinks in this case that you have not provided custom filtering.

Using this overload should fix the issue for your case:
```java
setDataProvider(DataProvider<T, C> dataProvider, SerializableFunction<String, C> filterConverter)
```

But this is still an issue. We need to think if there's a better way to recognize user-provided filters, so that your use-case would work.

> Another small issue (tell me if I need to open a new one) is when a ComboBox has a data provider set, it has the x icon to clear its value even if there is no value; the icon then disappears when you open and then close the dropdown.

Good catch! No need for a ticket, it was quick to fix #141

**Comment by heruan** [comment]
I understand! Indeed, using the specific overload works as expected. I agree this is still an issue since the user can provide a data provider which already filters by string and so it doesn't need the specific overload. But if a data provider is set, I would assume there is server-side filtering; otherwise, I would use `setItems`.

**Comment by Legioth** [comment]
We concluded that any variant that takes a `DataProvider<T, String>` or an item filter callback should *always* refer to the server-side data provider for filtering. Cases that *can*  filter on the client should be limited to the APIs using `ListDataProvider<T>` or any `setItems` variant, and are not using an item filter callback.

We should probably not add direct support for anything along the lines of `DataProvider<T, Void>` (or `DataProvider<T, ?>`). There are two reasons for this:
1) For this method to work in practice, it would have to eagerly load all items into server-side memory to be able to do any filtering. This might be quite unexpected for anyone who hasn't used the ComboBox from V10 or V11.
2) Type erasure means that `DataProvider<T, String>` and `DataProvider<T, Void>` are effectively the same thing. This in turn means that the method accepting `DataProvider<T, Void>` would have to have a different method name.

Not supporting `DataProvider<T, Void>` does slightly break backwards compatibility compared to V10 and V11, but it is in line with what was supported in V8. We might consider creating a shorthand for loading all items from a data provider to help migration, i.e. something like `comboBox.setItems(myDataProvider.fetchAll());`.
